GET localhost:8080/api/admin/products
Content-Type: application/json
###

PUT localhost:8080/api/products/1
Content-Type: application/json

{
  "price": 100500
}

###

POST localhost:8080/api/products
Content-Type: application/json

{
  "price": 100500
}
###
PATCH localhost:8080/api/products/1
Content-Type: application/json

{
  "category_id": 1,
  "name": "so much test"
}

###
GET localhost:8080/api/products/1
Content-Type: application/json

###

