name: run tests
on: [pull_request, pull_request_review]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: display github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: notify channel
      env:
        BOT_ID: ${{ secrets.TG_BOT_ID }}
        CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: bash .github/scripts/notify_tg.sh


