name: handle PR
on:
  pull_request:
    types: [opened, reopened, closed, review_requested, synchronize]
  pull_request_review:
    types: [submitted]
jobs:
  pr-notify:
    runs-on: ubuntu-latest

    steps:
    - name: display github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

# TODO: checkout only to access bash script, need to improve this
    - uses: actions/checkout@v2
    - uses: ./.github/actions/notify_tg
      with:
        message: |
          *event*: ${{ github.event.name }}
          *actor*: ${{ github.actor }}
          *action*: ${{ github.event.action }}
          "*PR*: [${{ github.event.pull_request.title }}](${{ github.event.pull_request._links.html.href }})"
        tg-bot-token: ${{ secrets.TG_BOT_ID }}
        channel-id: ${{ secrets.TG_CHAT_ID }}

      env:
#        TODO: uncomment after secrets are added to repo settings
#        BOT_ID: ${{ secrets.TG_BOT_ID }}
#        CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        PR_LINK: ${{ github.event.pull_request._links.html.href }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        ACTION: ${{ github.event.action }}
        MSG: |
          *event*: ${GITHUB_EVENT_NAME}
          *actor*: ${GITHUB_ACTOR}
          *action*: ${{ github.event.action }}
          "*PR*: [${{ github.event.pull_request.title }}](${{ github.event.pull_request._links.html.href }})"

#      run: bash .github/scripts/notify_tg.sh


