name: handle PR
on: pull_request
jobs:
  pr-notify:
    runs-on: ubuntu-latest

    steps:
    - name: display github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

# TODO: checkout only to access bash script, need to improve this
    - uses: actions/checkout@v2
    - name: notify channel
      env:
        BOT_ID: ${{ secrets.TG_BOT_ID }}
        CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        EVENT: ${{ github.event.action }}
      run: bash .github/scripts/notify_tg.sh


