name: run tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: testshop
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: run tests with maven
#      TODO: uncomment before merge !
      run: echo fake tests run
#      run: mvn test

    - name: check style
      run: mvn checkstyle:check

    - name: display github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: extract branch name
      id: extract_branch
      if: ${{ failure() }}
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

    - uses: ./.github/actions/notify_tg
      if: ${{ failure() }}
      with:
        message: |
          алярм!!! ${{ github.actor }} опять грохнул билд!
          *branch*: [${{ steps.extract_branch.outputs.branch }}](https://github.com/${{ github.repository }}/tree/${{ steps.extract_branch.outputs.branch }})
      env:
        BOT_ID: ${{ secrets.TG_BOT_ID }}
        CHAT_ID: ${{ secrets.TG_CHAT_ID }}

